# Web Application Firewall Configuration
# ModSecurity rules for Claude Talimat

SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess On
SecResponseBodyMimeType text/plain text/html text/xml application/json

# Core Rule Set
Include /etc/modsecurity/crs-setup.conf
Include /etc/modsecurity/rules/*.conf

# Custom Rules for Claude Talimat
SecRule REQUEST_URI "@contains /api/" \
    "id:1001,\
    phase:1,\
    block,\
    msg:'API endpoint access blocked',\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-protection',\
    ver:'OWASP_CRS/3.3.0',\
    severity:'CRITICAL',\
    setvar:'tx.anomaly_score_pl2=+%{tx.critical_anomaly_score}'"

# Rate Limiting
SecAction \
    "id:1002,\
    phase:1,\
    nolog,\
    pass,\
    t:none,\
    setvar:'tx.rate_limit=10',\
    setvar:'tx.rate_limit_window=60'"

# SQL Injection Protection
SecRule ARGS "@detectSQLi" \
    "id:1003,\
    phase:2,\
    block,\
    msg:'SQL Injection Attack Detected',\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-sqli',\
    ver:'OWASP_CRS/3.3.0',\
    severity:'CRITICAL',\
    setvar:'tx.anomaly_score_pl2=+%{tx.critical_anomaly_score}'"

# XSS Protection
SecRule ARGS "@detectXSS" \
    "id:1004,\
    phase:2,\
    block,\
    msg:'XSS Attack Detected',\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-xss',\
    ver:'OWASP_CRS/3.3.0',\
    severity:'CRITICAL',\
    setvar:'tx.anomaly_score_pl2=+%{tx.critical_anomaly_score}'"

# File Upload Protection
SecRule FILES_NAMES "@rx \\.(php|jsp|asp|aspx|sh|bat|exe)$" \
    "id:1005,\
    phase:2,\
    block,\
    msg:'Malicious file upload attempt',\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-fileupload',\
    ver:'OWASP_CRS/3.3.0',\
    severity:'CRITICAL',\
    setvar:'tx.anomaly_score_pl2=+%{tx.critical_anomaly_score}'"

# Authentication Bypass Protection
SecRule REQUEST_HEADERS:Authorization "@rx ^Bearer\s+[A-Za-z0-9+/=]+$" \
    "id:1006,\
    phase:1,\
    pass,\
    msg:'Valid JWT token format',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-authentication',\
    ver:'OWASP_CRS/3.3.0',\
    severity:'INFO'"

# DDoS Protection
SecRule IP:REQUEST_COUNT "@gt 100" \
    "id:1007,\
    phase:1,\
    block,\
    msg:'Potential DDoS attack detected',\
    logdata:'Request count: %{REQUEST_COUNT}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-ddos',\
    ver:'OWASP_CRS/3.3.0',\
    severity:'CRITICAL',\
    setvar:'tx.anomaly_score_pl2=+%{tx.critical_anomaly_score}'"

# Brute Force Protection
SecRule IP:FAILED_LOGIN_COUNT "@gt 5" \
    "id:1008,\
    phase:1,\
    block,\
    msg:'Brute force attack detected',\
    logdata:'Failed login count: %{FAILED_LOGIN_COUNT}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-bruteforce',\
    ver:'OWASP_CRS/3.3.0',\
    severity:'CRITICAL',\
    setvar:'tx.anomaly_score_pl2=+%{tx.critical_anomaly_score}'"

# Data Exfiltration Protection
SecRule RESPONSE_BODY "@rx (password|secret|key|token).*[:=].*[a-zA-Z0-9+/=]{20,}" \
    "id:1009,\
    phase:4,\
    block,\
    msg:'Potential data exfiltration detected',\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-dataexfiltration',\
    ver:'OWASP_CRS/3.3.0',\
    severity:'CRITICAL',\
    setvar:'tx.anomaly_score_pl2=+%{tx.critical_anomaly_score}'"

# Anomaly Scoring
SecRule TX:ANOMALY_SCORE "@ge %{tx.inbound_anomaly_score_threshold}" \
    "id:1010,\
    phase:2,\
    block,\
    msg:'Inbound Anomaly Score Exceeded (Total Score: %{TX.ANOMALY_SCORE})',\
    logdata:'Total Inbound Score: %{TX.ANOMALY_SCORE} (TX.inbound_anomaly_score_threshold=%{TX.INBOUND_ANOMALY_SCORE_THRESHOLD})',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'anomaly-evaluation',\
    ver:'OWASP_CRS/3.3.0',\
    severity:'CRITICAL'"

# Logging Configuration
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial
SecAuditLog /var/log/modsecurity/audit.log
