# =============================================================================
# ALERTMANAGER CONFIGURATION FOR CLAUDE TALİMAT
# =============================================================================

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@claude-talimat.com'
  smtp_auth_username: 'alerts@claude-talimat.com'
  smtp_auth_password: 'your-smtp-password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    group_wait: 5s
    repeat_interval: 30m
  - match:
      severity: warning
    receiver: 'warning-alerts'
    group_wait: 10s
    repeat_interval: 1h
  - match:
      service: 'database'
    receiver: 'database-alerts'
  - match:
      service: 'frontend'
    receiver: 'frontend-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5001/webhook'
    send_resolved: true

- name: 'critical-alerts'
  email_configs:
  - to: 'admin@claude-talimat.com'
    subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Service: {{ .Labels.service }}
      Instance: {{ .Labels.instance }}
      Time: {{ .StartsAt }}
      {{ end }}
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    channel: '#alerts'
    title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Service:* {{ .Labels.service }}
      *Instance:* {{ .Labels.instance }}
      {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: 'admin@claude-talimat.com'
    subject: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Service: {{ .Labels.service }}
      Instance: {{ .Labels.instance }}
      Time: {{ .StartsAt }}
      {{ end }}

- name: 'database-alerts'
  email_configs:
  - to: 'dba@claude-talimat.com'
    subject: '🗄️ DATABASE: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Database Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Database: {{ .Labels.database }}
      Instance: {{ .Labels.instance }}
      Time: {{ .StartsAt }}
      {{ end }}

- name: 'frontend-alerts'
  email_configs:
  - to: 'frontend@claude-talimat.com'
    subject: '🌐 FRONTEND: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Frontend Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Service: {{ .Labels.service }}
      Instance: {{ .Labels.instance }}
      Time: {{ .StartsAt }}
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
  - source_match:
      alertname: 'ServiceDown'
    target_match:
      alertname: 'HighResponseTime'
    equal: ['service', 'instance']
